import { getDb, getImagesDir } from "@/lib/db";
import { NextResponse } from "next/server";
import archiver from "archiver";
import path from "path";
import fs from "fs";
import { Readable } from "stream";

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const db = getDb();

  const pkg = db
    .prepare(
      `SELECT p.*, g.score, n.theme, n.keywords
       FROM packages p
       JOIN gaps g ON p.gap_id = g.id
       JOIN narratives n ON g.narrative_id = n.id
       WHERE p.id = ?`
    )
    .get(id) as Record<string, unknown> | undefined;

  if (!pkg) {
    return NextResponse.json({ error: "Package not found" }, { status: 404 });
  }

  const imageUrls: string[] = JSON.parse(pkg.image_urls as string);
  const talkingPoints: string[] = JSON.parse(pkg.talking_points as string);

  // Build ZIP in memory
  const archive = archiver("zip", { zlib: { level: 9 } });
  const chunks: Buffer[] = [];

  archive.on("data", (chunk: Buffer) => chunks.push(chunk));

  // Add metadata JSON
  const metadata = {
    tokenName: pkg.token_name,
    ticker: pkg.ticker,
    tagline: pkg.tagline,
    description: pkg.description,
    talkingPoints,
    launchStrategy: pkg.launch_strategy,
    narrative: pkg.theme,
    keywords: JSON.parse(pkg.keywords as string),
    gapScore: pkg.score,
    generatedAt: pkg.generated_at,
  };
  archive.append(JSON.stringify(metadata, null, 2), {
    name: "metadata.json",
  });

  // Add Four.meme listing description
  const listing = `# ${pkg.token_name} ($${pkg.ticker})

${pkg.tagline}

## About
${pkg.description}

## Why ${pkg.ticker}?
${talkingPoints.map((tp) => `- ${tp}`).join("\n")}

## Launch Strategy
${pkg.launch_strategy}

---
Generated by MemeForge — AI Narrative Arbitrage Engine
Narrative: ${pkg.theme}
Gap Score: ${pkg.score}
`;
  archive.append(listing, { name: "four-meme-listing.md" });

  // Add images
  const imagesDir = getImagesDir();
  for (const imageUrl of imageUrls) {
    const filename = path.basename(imageUrl);
    const filePath = path.join(imagesDir, filename);
    if (fs.existsSync(filePath)) {
      archive.file(filePath, { name: `images/${filename}` });
    }
  }

  await archive.finalize();

  // Wait for all chunks
  await new Promise<void>((resolve) => archive.on("end", resolve));

  const buffer = Buffer.concat(chunks);
  const safeTicker = (pkg.ticker as string).replace(/[^a-zA-Z0-9]/g, "");

  return new Response(buffer, {
    headers: {
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="${safeTicker}-launch-package.zip"`,
    },
  });
}
